### ISSUE TITLE
No source for visibility()

### ISSUE THREAD

**Issue by mootari** [observablehq/stdlib#106]
`visibility()` is documented in `README.md`, but nowhere present in the source. The source link in the documentation points to `width`.

**Comment by mootari** [comment]
The source is a bit spread in `stdlib/runtime`, but a candidate line might be [runtime.js#206](https://github.com/observablehq/runtime/blob/master/src/runtime.js#L206) ([permalink](https://github.com/observablehq/runtime/blob/5f36141454c9d08221cdafed0843699ff39ccb44/src/runtime.js#L206)).

**Comment by mbostock** [comment]
Visibility is a “special” because it is scoped to a single cell, similar to the invalidation promise. 5e implementation is here:

https://github.com/observablehq/runtime/blob/5f36141454c9d08221cdafed0843699ff39ccb44/src/runtime.js#L172

**Comment by mbostock** [comment]
I’ve added the link to the source in runtime.
