### ISSUE TITLE
Using DOM from Library

### ISSUE THREAD

**Issue by menghaniryan** [observablehq/stdlib#140]
I'm trying to use the Observable standard library to creatre a Bubble Chart.

I've added the following code at the top of my js file (I am working in React):

`import {Library} from '@observablehq/stdlib/';`

which is working correctly. However, I want to access the DOM functions from the Library. I do this by trying the following statement:

`Library.DOM.uid("My stuff")`

but I am getting an error that DOM is undefined. Am I using the Library incorrectly?

**Comment by tmcw** [comment]
Please check out the last section of [the readme](https://github.com/observablehq/stdlib#Library) you'll need to call `new Library()` to construct an instance.

**Comment by menghaniryan** [comment]
Wow, I didn't see the installation part of the README. Thanks so much!

**Comment by amarder** [comment]
Hmmm. When I do this I get `TypeError: library.DOM is undefined`.
