### ISSUE TITLE
Use case of lib

### ISSUE THREAD

**Issue by tryhardest** [observablehq/stdlib#158]
I was searching for a library that could help determine what was the root (exact) cause of a DOM layout invalidation and prompt for repaint.

I came across this. But in looking at it I was intrigued. Would I be right to think this is a library primarily used for if someone was using the observable pattern? Are there any other main use cases for this lib? Tnx

**Comment by mbostock** [comment]
The is the standard library for [Observable notebooks](https://observablehq.com), so, I’m not sure if that’s what you’re looking for? If it is, feel free to post in [our forum](https://talk.observablehq.com) to ask for help getting started!
