### ISSUE TITLE
Any API to show the contents of the document?

### ISSUE THREAD

**Issue by JackieAnxis** [observablehq/stdlib#183]
Is there any API to show the contents of the document? 
There would be several `<h1>`, `<h2>`, `<h3>` and so on titles in one document, I want to show an overview of the contents in the begining of my document, is there any functions?

**Comment by mbostock** [comment]
Do these help?

https://observablehq.com/@mbostock/toc
https://observablehq.com/@nebrius/indented-toc

**Comment by JackieAnxis** [comment]
> Do these help?
> 
> https://observablehq.com/@mbostock/toc
> https://observablehq.com/@nebrius/indented-toc

Thanks, it works!
