### ISSUE TITLE
[observablehq.com] homepage incorrectly shows no notebooks

### ISSUE THREAD

**Issue by ericsoco** [observablehq/stdlib#189]
Leaving here because I can't find a repo for the website.

I logged into observablehq for the first time in much too long, and saw:
<img width="964" alt="Screen Shot 2020-10-24 at 1 52 40 PM" src="https://user-images.githubusercontent.com/1127259/97093469-151e0780-1601-11eb-8c46-d5b7196bdd78.png">

...freaked out for a bit, then clicked on Notebooks in left-nav, and saw all my notebooks as expected.

**Comment by annie** [comment]
responded here! https://talk.observablehq.com/t/bug-reports-here/4057

closing this issue since it's not related to stdlib.
