### ISSUE TITLE
Signup with Google causing change to personal gmail password 

### ISSUE THREAD

**Issue by JorinHakai** [observablehq/stdlib#195]
The flow for signing up for an account with ObservableHQ is confusing enough that I just accidentally changed the password to my google account. I've had to re-log everything with 2 factor authentication now. Why is it possible to change my personal email password during a signup process to the site? Seems like an option that should be turned off if possible.

**Comment by mbostock** [comment]
Hi @JorinHakai. Please email us at support at observablehq.com if you’d like help. We don’t control Google’s user interface, so I can’t really say why Google would encourage you to change your password as part of signing-in to Google.
