### ISSUE TITLE
Support opening remote SQLite databases and export

### ISSUE THREAD

**Issue by john-guerra** [observablehq/stdlib#225]
Loading sqlite databases from FileAttachments it is very convenient, but greatly limits the use of the library. It would be nice to easily load remote databases as @mbostock demonstrated in the original [sqlite](https://observablehq.com/@mbostock/sqlite)

I'm thinking something like `SQLiteDatabaseClient.open` that does:

```js
  async open(url) {
     const  db = new SQLite.Database(
        new Uint8Array( await fetch(url).then(res => res.arrayBuffer() ) )
      );
     return new SQLiteDatabaseClient(db);   
```

Also an `export` that does something like `this._db.export()`, and even better a `download()` that does the whole `DOM.download(async () => new Blob([await db._db.export()]), "mydb.db")` as I did in my [export example ](https://observablehq.com/@john-guerra/save-modified-sqlite-file)

Also, for me it has been very confusing what the SQLite object in a new notebook is. If I'm understanding correctly, it is just sql.js right? It would be nice to have also a method of creating a new Database as in `new SQLite.Database()` but actually getting a database client object. 

BTW I cannot access [SQLiteDatabaseClient](https://github.com/observablehq/stdlib/blob/8945d7b50af738c87afe7d418c36802257165da5/src/sqlite.js#L6) from a notebook, right?

**Comment by mbostock** [comment]
> Also, for me it has been very confusing what the SQLite object in a new notebook is. If I'm understanding correctly, it is just sql.js right?

Yes, as documented here: https://observablehq.com/@observablehq/recommended-libraries 

> BTW I cannot access SQLiteDatabaseClient from a notebook, right?

Not currently but I agree it would be nice to expose this functionality.
