### ISSUE TITLE
Add Arquero as a recommended library

### ISSUE THREAD

**Issue by mbostock** [observablehq/stdlib#229]

**Comment by abitrolly** [comment]
Will there be a tutorial on how to use it? For example, how to inspect tables with Arquero.

**Comment by mbostock** [comment]
You can pass an Arquero table to [Inputs.table](https://observablehq.com/@observablehq/input-table).

**Comment by abitrolly** [comment]
I ended up importing `aq` from https://observablehq.com/@uwdata/arquero where it has `.view()` method.
