### ISSUE TITLE
Update D3 to 7.0, Plot to 0.2, and HTL to 0.3

### ISSUE THREAD

**Issue by mbostock** [observablehq/stdlib#230]
The major changes in 7.0 are mostly in regard to the adoption of type: module and requirement of Node 12.x, but there are some small other changes to d3.bin and d3.ascending/d3.descending. Should we upgrade anyway? Or should we wait until we have version pinning.

**Comment by Fil** [comment]
We can introduce the mode reducer later, or by copying the code into Plot, that's not blocking for Plot. My preference nonetheless would go to upgrading now, if the risk is acceptable. (Sorry for the useless comment ;-) )

**Comment by mbostock** [comment]
This should happen at the same time we upgrade Plot to 0.2 and HTL to 0.3.

**Comment by mbostock** [comment]
Fixed in #242.
