### ISSUE TITLE
Import the observablehq in a Vue project using webpack

### ISSUE THREAD

**Issue by Sheldon04** [observablehq/stdlib#269]
I tried to load the js files with babel-loader, but it came with the following problem:
===========================================================
 error  in ./node_modules/@observablehq/stdlib/src/library.js

Module parse failed: Unexpected token (25:61)
You may need an appropriate loader to handle this file type.
|     FileAttachment: () => NoFileAttachments,
|     Arrow: () => require(arrow.resolve()),
|     Inputs: () => require(inputs.resolve()).then(Inputs => ({...Inputs, file: Inputs.fileOf(AbstractFile)})),
|     Mutable: () => Mutable,
|     Plot: () => require(plot.resolve()),

**Comment by mbostock** [comment]
Sorry, but I don’t know how to debug this.
