### ISSUE TITLE
README: Incorrect links to source

### ISSUE THREAD

**Issue by kentr** [observablehq/stdlib#298]
Links to source in the `File Attachments` section of the `README` are to a non-existent file, `src/fileAttachment.js`. 

Should they link to `src/fileAttachment.mjs` instead?

[Example](https://github.com/observablehq/stdlib/blob/3edd83315db9aa8c3b525c2e4d179f5fa56b17ca/README.md?plain=1#L283)

```markdown
[<>](https://github.com/observablehq/stdlib/blob/master/src/fileAttachment.js "Source")
```

**Comment by mbostock** [comment]
Fixed in #316.
