### ISSUE TITLE
Greater than filter shouldn't remove NaN values

### ISSUE THREAD

**Issue by mkfreeman** [observablehq/stdlib#339]
It feels odd that adding a greater than filter removes `NaN` values (which we bin into the _invalid number_ category). 

I would expect the `NaN` values to still be visible after applying this (persistent filter):

**no filter:**
![Image](https://user-images.githubusercontent.com/1373882/208118989-f37630b2-8d78-43ef-a463-94b7ba24a463.png)

**with filter:** (notice yellow bar is missing, as are `NaN` values from the table rows)

![Image](https://user-images.githubusercontent.com/1373882/208119157-8974304c-44ef-49aa-b96d-bbcb7677761c.png)

**Comment by mbostock** [comment]
This seems like the desired behavior to me. Comparing anything with NaN is always false, so all undefined/null/NaN vales should be removed with any threshold comparison (>, <, >=, <=).

```js
[1, 2, 3, 4, NaN].filter((x) => x > 2) // [3, 4]
```

**Comment by annie** [comment]
@mkfreeman do we still want to modify this behavior, or can we close this issue?
