### ISSUE TITLE
DOM.image

### ISSUE THREAD

**Issue by tmcw** [observablehq/stdlib#59]
I find myself doing this fairly often:

```js
{
  let im = new Image();
  im.src = 'https://file-iiwfdmgpik.now.sh/';
  return new Promise((resolve, reject) => {
    im.onload = () => {
      resolve(im);
    };
    im.onerror = reject;
  });
}
```

Just throwing it out there, but it'd be nice if there was a DOM.image method that was able to load an image like this - properly handling errors and awaiting the image's load state.

**Comment by mbostock** [comment]
See [d3.image](https://github.com/d3/d3-fetch/blob/master/README.md#image).

By the same measure, I use [d3.json](https://github.com/d3/d3-fetch/blob/master/README.md#json) a ton, even though it’s a (relatively) trivial wrapper on top of fetch.

**Comment by mbostock** [comment]
As a tiny variation, I often style the image to make a little icon, which is useful if you’re going to do something to the image before displaying it:

```js
image = new Promise((resolve, reject) => {
  const image = new Image;
  image.src = url;
  image.style.height = "33px";
  image.style.display = "block";
  image.onload = () => resolve(image);
  image.onerror = reject;
})
```

Also, sometimes you want [*image*.crossOrigin = "anonymous"](https://beta.observablehq.com/@mbostock/cross-origin-images).
